"""
train_dna_validation.py — Train independent validation CNN regressors for DNA tasks.

Purpose: reward-hacking ablation. Sequences generated by optimize_dna.py are
         evaluated by this independently-trained model. If the optimization oracle
         is exploiting model artifacts rather than finding real high-expression
         sequences, the validation model will give low scores.

Key differences from train_cnn_dna.py (DNARegressor):
  - 4 conv layers (vs 3) with larger kernels: 19, 13, 9, 7
  - Larger channels: 192 → 256 → 320 → 320
  - Dual global pooling: max + mean concatenated → 640-dim feature
  - 3-layer regression head: 640 → 256 → 64 → 1
  - Different seed (default 99 vs 42) → different weight init AND train/val/test split

Usage:
  python train_dna_validation.py --task hepG2
  python train_dna_validation.py --task all
"""

from __future__ import annotations

import argparse
import random
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import pearsonr, spearmanr

import torch
import torch.nn as nn
from torch.cuda.amp import GradScaler, autocast
from torch.utils.data import DataLoader
from tqdm import tqdm

# Reuse data utilities from the original training script
import sys
SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))
from train_cnn_dna import (
    DATA_DIR, TASKS, DNADataset, collate_fn,
    load_task_frame, deduplicate_and_split,
    is_valid_dna, encode_dna,
)

OUT_ROOT    = SCRIPT_DIR.parents[2] / "data" / "Big_Oracles" / "DNA" / "cnn_dna_models_v2"
BATCH_SIZE  = 128
EPOCHS      = 20
LR          = 5e-4       # slightly lower than original (1e-3)
WEIGHT_DECAY = 1e-4
NUM_WORKERS = 4
FP16        = True
SEED        = 99         # different from original (42) → independent split + init

loss_fn = nn.MSELoss()


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--task",         default="all", choices=["all", *TASKS])
    p.add_argument("--epochs",       type=int,   default=EPOCHS)
    p.add_argument("--batch_size",   type=int,   default=BATCH_SIZE)
    p.add_argument("--lr",           type=float, default=LR)
    p.add_argument("--weight_decay", type=float, default=WEIGHT_DECAY)
    p.add_argument("--num_workers",  type=int,   default=NUM_WORKERS)
    p.add_argument("--seed",         type=int,   default=SEED)
    return p.parse_args()


def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


# ── Validation model (larger, architecturally distinct) ──────────────────────

class DNARegressorV2(nn.Module):
    """
    Larger CNN for independent validation.

    Changes vs DNARegressor:
      - 4 conv layers, kernels 19/13/9/7 (vs 3 layers, 15/11/7)
      - Wider channels: 192→256→320→320 (vs 128→192→256)
      - Dual global pooling: cat(max, mean) → 640-dim (vs max-only → 256-dim)
      - 3-layer head: 640→256→64→1 (vs 2-layer: 256→128→1)
    """

    def __init__(self, dropout: float = 0.15):
        super().__init__()
        self.conv1 = nn.Sequential(
            nn.Conv1d(4,   192, kernel_size=19, padding="same"),
            nn.BatchNorm1d(192),
            nn.GELU(),
            nn.MaxPool1d(2),
            nn.Dropout(dropout),
        )
        self.conv2 = nn.Sequential(
            nn.Conv1d(192, 256, kernel_size=13, padding="same"),
            nn.BatchNorm1d(256),
            nn.GELU(),
            nn.MaxPool1d(2),
            nn.Dropout(dropout),
        )
        self.conv3 = nn.Sequential(
            nn.Conv1d(256, 320, kernel_size=9, padding="same"),
            nn.BatchNorm1d(320),
            nn.GELU(),
            nn.MaxPool1d(2),
            nn.Dropout(dropout),
        )
        self.conv4 = nn.Sequential(
            nn.Conv1d(320, 320, kernel_size=7, padding="same"),
            nn.BatchNorm1d(320),
            nn.GELU(),
            nn.Dropout(dropout),
        )
        # dual pooling → 320*2 = 640 features
        self.head = nn.Sequential(
            nn.Linear(640, 256),
            nn.GELU(),
            nn.Dropout(0.2),
            nn.Linear(256, 64),
            nn.GELU(),
            nn.Dropout(0.1),
            nn.Linear(64, 1),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        h = self.conv1(x)
        h = self.conv2(h)
        h = self.conv3(h)
        h = self.conv4(h)
        h_max  = h.max(dim=-1).values    # (B, 320)
        h_mean = h.mean(dim=-1)          # (B, 320)
        h_pool = torch.cat([h_max, h_mean], dim=-1)   # (B, 640)
        return self.head(h_pool).squeeze(-1)


# ── Evaluate ─────────────────────────────────────────────────────────────────

@torch.no_grad()
def evaluate(model, loader, device, mean, std, fp16):
    model.eval()
    preds_norm, trues_norm = [], []
    for batch in tqdm(loader, desc="Evaluating"):
        x = batch["x"].to(device)
        y = batch["label"].to(device)
        with autocast(enabled=fp16):
            pred = model(x)
        preds_norm.append(pred.cpu())
        trues_norm.append(y.cpu())

    preds_norm = torch.cat(preds_norm).numpy()
    trues_norm = torch.cat(trues_norm).numpy()
    preds = preds_norm * std + mean
    trues = trues_norm * std + mean

    rmse     = float(np.sqrt(np.mean((preds - trues) ** 2)))
    r, _     = pearsonr(preds, trues)
    rho, _   = spearmanr(preds, trues)
    return {"rmse": rmse, "pearson": float(r), "spearman": float(rho)}


# ── Train one task ────────────────────────────────────────────────────────────

def train_one_task(task: str, args):
    out_dir = OUT_ROOT / task
    out_dir.mkdir(parents=True, exist_ok=True)

    df = load_task_frame(task)
    # Different seed → different train/val/test split from the original model
    train_df, valid_df, test_df = deduplicate_and_split(df, args.seed)

    train_df.to_csv(out_dir / "train.csv", index=False)
    valid_df.to_csv(out_dir / "valid.csv", index=False)
    test_df.to_csv(out_dir  / "test.csv",  index=False)

    mean_score = float(train_df["score"].mean())
    std_score  = float(train_df["score"].std())
    np.save(out_dir / "normalization.npy", np.array([mean_score, std_score]))

    print(f"\nTask: {task}")
    print(f"Train: {len(train_df):,}  Val: {len(valid_df):,}  Test: {len(test_df):,}")
    print(f"score mean={mean_score:.4f}  std={std_score:.4f}")

    train_ds = DNADataset(train_df, mean_score, std_score)
    valid_ds = DNADataset(valid_df, mean_score, std_score)
    test_ds  = DNADataset(test_df,  mean_score, std_score)

    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True,
                              num_workers=args.num_workers, collate_fn=collate_fn,
                              pin_memory=True)
    valid_loader = DataLoader(valid_ds, batch_size=args.batch_size, shuffle=False,
                              num_workers=args.num_workers, collate_fn=collate_fn)
    test_loader  = DataLoader(test_ds,  batch_size=args.batch_size, shuffle=False,
                              num_workers=args.num_workers, collate_fn=collate_fn)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model  = DNARegressorV2().to(device)
    n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"Trainable parameters: {n_params / 1e6:.2f}M  (vs ~0.66M for DNARegressor)")

    optimizer = torch.optim.AdamW(model.parameters(),
                                  lr=args.lr, weight_decay=args.weight_decay)
    scaler    = GradScaler(enabled=FP16)

    best_val_spearman = -np.inf
    log_rows = []

    for epoch in tqdm(range(1, args.epochs + 1), desc=f"{task} epochs"):
        model.train()
        for batch in tqdm(train_loader, desc=f"{task} epoch {epoch}", leave=False):
            x = batch["x"].to(device, non_blocking=True)
            y = batch["label"].to(device, non_blocking=True)
            optimizer.zero_grad()
            with autocast(enabled=FP16):
                pred = model(x)
                loss = loss_fn(pred, y)
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            scaler.step(optimizer)
            scaler.update()

        val_metrics = evaluate(model, valid_loader, device, mean_score, std_score, FP16)
        print(f"{task} epoch {epoch}: val spearman={val_metrics['spearman']:.4f}")

        log_rows.append({"epoch": epoch, **val_metrics})
        pd.DataFrame(log_rows).to_csv(out_dir / "training_log.csv", index=False)

        if val_metrics["spearman"] > best_val_spearman:
            best_val_spearman = val_metrics["spearman"]
            torch.save({
                "epoch":   epoch,
                "model":   model.state_dict(),
                "optim":   optimizer.state_dict(),
                "metrics": val_metrics,
                "task":    task,
                "seed":    args.seed,
            }, out_dir / "best_model.pt")
            print(f"Saved best model for {task} at epoch {epoch} "
                  f"(val spearman={best_val_spearman:.4f})")

    print(f"\nLoading best checkpoint for {task} test evaluation...")
    ckpt = torch.load(out_dir / "best_model.pt", map_location=device, weights_only=False)
    model.load_state_dict(ckpt["model"])

    test_metrics = evaluate(model, test_loader, device, mean_score, std_score, FP16)
    pd.DataFrame([test_metrics]).to_csv(out_dir / "test_results.csv", index=False)
    print(
        f"{task} test: spearman={test_metrics['spearman']:.4f} "
        f"pearson={test_metrics['pearson']:.4f} rmse={test_metrics['rmse']:.4f}"
    )


def main():
    args = parse_args()
    set_seed(args.seed)
    tasks = TASKS if args.task == "all" else [args.task]
    for task in tasks:
        train_one_task(task, args)


if __name__ == "__main__":
    main()
